import { getBlogPostById } from '@/lib/blog-data';
import { canonicalUrl } from '@/lib/seo';

export type EvidenceLevel = 'peer-reviewed' | 'preprint' | 'institutional' | 'documentation';

export const researchIndexUpdatedAt = '2026-08-22';

export interface ResearchIndexEntry {
  id: string;
  title: string;
  url: string;
  year: number;
  publisher: string;
  sourceTitle: string;
  sourceUrl: string;
  sensorPrinciple: string;
  modalities: string[];
  formFactor: string;
  dataOutput: string;
  applications: string[];
  evidence: EvidenceLevel;
  limitations: string;
  reviewedAt: string;
}

type ResearchIndexSupplement = Omit<
  ResearchIndexEntry,
  'id' | 'title' | 'url' | 'sourceTitle' | 'sourceUrl'
> & { id: string };

function toEntry(supplement: ResearchIndexSupplement): ResearchIndexEntry {
  const post = getBlogPostById(supplement.id);

  if (!post) {
    throw new Error(`Research index references missing article: ${supplement.id}`);
  }

  return {
    ...supplement,
    title: post.title,
    url: canonicalUrl(`/research/${post.id}`),
    sourceTitle: post.sourceTitle,
    sourceUrl: post.sourceUrl,
  };
}

const supplements: ResearchIndexSupplement[] = [
  {
    id: 'univtac-platform-encoder-benchmark-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Simulation-generated marker-based visuo-tactile observations encoded by a 512-dimensional ResNet-18 representation model with shape, contact-deformation, marker-position, and relative-pose supervision',
    modalities: ['simulated marked tactile RGB', 'simulated marker-free tactile RGB', 'simulation depth', 'projected marker coordinates', 'relative object pose', 'robot vision and state', 'physical ViTai GF225 tactile RGB at 30 Hz'],
    formFactor: 'Simulated bilateral GelSight Mini on a Franka Panda benchmark configuration plus a separate physical Tianji Marvin arm with bilateral ViTai GF225 sensors',
    dataOutput: '205,826 encoder-pretraining samples; an eight-task benchmark; a pinned public 800-episode HDF5 release; 512-dimensional tactile features; and protocol-bounded simulated and physical policy success rates',
    applications: ['visuo-tactile simulation', 'tactile representation learning', 'contact-rich robot manipulation', 'tactile benchmark evaluation', 'sim-to-real manipulation'],
    evidence: 'preprint',
    limitations: 'UniVTAC is a February 10, 2026 arXiv v1 preprint. Its 205,826 encoder samples, 400 paper policy-training trajectories, public 800-episode benchmark release, 450 physical demonstrations, and evaluation rollouts are different units. Paper Table I reports 30.9% for vision-only ACT and 48.0% with the UniVTAC Encoder, a 17.1-percentage-point change; hosted checkpoint logs instead average 32.375 and 43.5 and should not be described as reproducing that table. The public workflow currently supports simulated GelSight Mini collection and evaluation, while GF225 and Xense paths remain marked planned or TODO. Repository, dataset, and checkpoint licensing also require separate treatment.',
    reviewedAt: '2026-08-22',
  },
  {
    id: 'vision-based-tactile-intelligence-robotics-survey-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Review taxonomy of camera-based tactile sensing that converts compliant-interface deformation into optical images for geometric, force-related, temporal, and learned inference',
    modalities: ['tactile image', 'direct contact geometry', 'model-mediated force-related cues', 'temporal contact and slip information', 'vision-touch-language-action alignment'],
    formFactor: 'Survey spanning fingertip, manipulator-integrated, miniature, all-around, and large-area vision-based tactile sensor designs',
    dataOutput: 'Source-organized map from contact deformation and optical readout through tactile representations, multimodal learning, simulation, datasets, and manipulation policies',
    applications: ['vision-based tactile sensing', 'contact-rich manipulation', 'tactile representation learning', 'tactile foundation models', 'robot skin research mapping'],
    evidence: 'preprint',
    limitations: 'This August 16, 2026 arXiv v1 source is a review rather than an original controlled benchmark, sensor release, dataset, or model artifact. Its taxonomy synthesizes prior literature and is not an industry standard; individual performance, availability, license, and scale claims still require the cited primary sources. No dedicated official project, code, or dataset link was displayed on the reviewed arXiv record on 2026-08-22.',
    reviewedAt: '2026-08-22',
  },
  {
    id: 'adept-visuo-tactile-dexterity-rl-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Per-finger TacMap encoding of vision-based fingertip penetration depth, thresholded contact, and fingertip position for the Flexiv-Sharpa student only',
    modalities: ['two RGB camera views', 'robot proprioception', 'five fingertip TacMap representations on Flexiv-Sharpa', 'five fingertip positions on Flexiv-Sharpa', 'joint-space robot action'],
    formFactor: 'Separate fixed-workbench KUKA iiwa7 plus Allegro Hand and Flexiv Rizon plus Sharpa-hand research configurations',
    dataOutput: 'Embodiment-specific reinforcement-learning policies mediated by a full joint-configuration-space geometric fabric',
    applications: ['dexterous insertion', 'long-horizon manipulation', 'visuo-tactile robot learning', 'zero-shot sim-to-real policy transfer'],
    evidence: 'preprint',
    limitations: 'The matched tactile comparison is restricted to one Flexiv-Sharpa square-and-round insertion condition with ten physical trials per modality: 3/10 final success for vision-only and 8/10 for visuo-tactile. Each task and embodiment is trained independently; KUKA experiments are vision-only; both systems are fixed workbenches; and no public training code, weights, checkpoint, dataset, or artifact license was verified on 2026-08-22.',
    reviewedAt: '2026-08-22',
  },
  {
    id: 'prism-contact-rich-industrial-skill-dataset-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Synchronized multi-view RGB-D, high-rate force/torque, robot state, and subset-only visuotactile sensing across industrial teleoperation platforms',
    modalities: ['multi-view RGB', 'depth', 'visuotactile image when available', '6DoF force/torque when available', 'robot joint angle and torque', 'end-effector pose', 'gripper state', 'human control signal', 'calibration and timestamps'],
    formFactor: 'Contact-rich industrial data collection across dual Franka Emika Panda, bimanual Realman RM75-6F, and LEJU upper-body humanoid platforms',
    dataOutput: '5,000+ robot trajectories paired with 5,000 human demonstrations, 45+ hours, and approximately 27M images across visual and visuotactile streams',
    applications: ['industrial robot learning', 'contact-rich manipulation', 'multimodal policy evaluation', 'teleoperation data analysis'],
    evidence: 'preprint',
    limitations: 'The tactile stream covers only an unspecified subset of episodes, and the approximately 27M images combine visual and visuotactile streams. Although the abstract says the dataset is open-sourced, the official project still labels the dataset “soon” and the GitHub repository exposes no dataset files, release, or dataset-file license as of 2026-08-22. Author-reported policy experiments remain tied to selected Realman tasks and are not an independent benchmark.',
    reviewedAt: '2026-08-22',
  },
  {
    id: 'missing-touch-spatial-tactile-feedback-teleoperation-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'GelSight Mini contact images mapped to a 32-DoF spatially programmable cutaneous fingertip display with bilateral kinesthetic force feedback',
    modalities: ['vision-based tactile image', 'binary spatial cutaneous feedback pattern', 'kinesthetic force feedback', '2D end-effector trajectory', 'participant questionnaire'],
    formFactor: 'Custom 2-DoF leader-follower telemanipulator evaluated with button discrimination and peg rolling',
    dataOutput: '50 Hz trajectories, DTW similarity to direct manipulation, task-specific errors, completion time, variability, and perceived workload',
    applications: ['robot teleoperation', 'haptic feedback', 'learning-from-demonstration data collection', 'contact-rich manipulation'],
    evidence: 'preprint',
    limitations: 'The abstract’s 29–79% reduction refers to deviation between teleoperated and natural trajectories under study-specific DTW comparisons, not autonomous-policy success or a universal dexterity gain. Evidence comes from a 2-DoF device, two tasks, 12 button-task participants and a separate 10-person peg-rolling group; Full feedback was not superior in every corrected comparison, and no autonomous policy was trained or evaluated.',
    reviewedAt: '2026-08-22',
  },
  {
    id: 'tac4loco-plantar-tactile-humanoid-locomotion-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Topology-preserving ordinal encoding of bilateral plantar pressure with state-conditioned spatial and temporal pressure-proprioception branches',
    modalities: ['60-element FSR pressure array per foot', 'proprioception', 'pressure history', 'simulated contact force', 'whole-body joint action'],
    formFactor: 'Unitree G1 trained in MJLab simulation and deployed physically with bilateral plantar-pressure insoles',
    dataOutput: 'Spatial and temporal plantar-support representations fused into a 50 Hz learned locomotion policy',
    applications: ['humanoid locomotion', 'post-contact terrain adaptation', 'plantar tactile sensing', 'sim-to-real control'],
    evidence: 'preprint',
    limitations: 'Tac4Loco is an arXiv v1 preprint on one Unitree G1 and one bilateral 60-taxel-per-foot FSR layout. Training occurs in simulation; physical comparisons generally use ten trials per configuration; the gravel demonstration is qualitative; and “zero-shot” refers only to the paper’s unseen compliant and granular conditions. Code and experiment configurations are announced for future release, but no dedicated artifact repository or license was verified on 2026-08-22.',
    reviewedAt: '2026-08-22',
  },
  {
    id: 'softvtbench-deformation-aware-visuo-tactile-dataset-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Simulated dual-finger GelSight Mini RGB and marker-motion rendering with evaluator-only FEM deformation state',
    modalities: ['simulated multi-view RGB', 'simulated tactile RGB', 'simulated tactile marker motion', 'proprioception', 'language', 'robot actions', 'evaluator-only FEM state'],
    formFactor: 'Isaac Sim and Isaac Lab deformable-object manipulation with a simulated Franka arm, Panda gripper, and bilateral GelSight Mini profiles',
    dataOutput: 'Expert demonstration trajectories plus Task Success Rate, Deformation-aware Success Rate, and normalized deformation traces',
    applications: ['deformable-object manipulation', 'visuo-tactile policy learning', 'interaction-quality evaluation'],
    evidence: 'preprint',
    limitations: 'The paper and Hugging Face dataset-card revision fd2793a describe 4,000 demonstrations, while the older GitHub README still lists 1,628 demonstrations and 33 assets; the first-party release documents are not synchronized. All data and evaluation are simulated, no SoftVTBench-specific sim-to-real validation is reported, and DSR is a paper-defined metric rather than an industry standard.',
    reviewedAt: '2026-08-22',
  },
  {
    id: 'hitac-wam-hierarchical-tactile-world-action-model-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Hierarchical tactile forecasting from contact state to 3D deformation and slip risk',
    modalities: ['video context', 'robot action chunks', 'contact state', '3D tactile deformation', 'slip risk'],
    formFactor: 'Contact-rich robot manipulation evaluated on chip grasping, blackboard erasing, and USB insertion',
    dataOutput: 'Candidate-conditioned tactile forecasts, task-progress estimates, selected action chunks, and discrepancy-triggered replanning signals',
    applications: ['contact-aware planning', 'tactile world-action modeling', 'online manipulation correction'],
    evidence: 'preprint',
    limitations: 'Author-reported evidence from three task-specific real-robot setups and matched training budgets; cross-hardware transfer, independent replication, and a public code or dataset release were not established on the reviewed source page.',
    reviewedAt: '2026-08-21',
  },
  {
    id: 't-rex-tactile-reactive-dexterous-manipulation-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Variable-rate visual-language-action modeling with a temporal tactile VQ-VAE',
    modalities: ['vision', 'language instruction', 'robot action', 'high-frequency tactile signal'],
    formFactor: 'Tactile-reactive dexterous manipulation across 12 author-reported tasks',
    dataOutput: 'Temporal tactile tokens and action predictions trained with a reported 100-hour collection; the official dataset card now exposes 5,464 episodes and 5,473,459 frames at 30 FPS, approximately 50 hours, in a LeRobot v3.0 subset',
    applications: ['delicate force control', 'deformable-object manipulation', 'tactile-reactive VLA policies'],
    evidence: 'preprint',
    limitations: 'The authors report 65% average success for T-Rex versus 35% for EgoScale, an absolute gap of 30 percentage points across 12 tasks with 16 rollouts per task. The result is tied to one Dexmate Vega-1 and Sharpa Wave setup, and the approximately 50-hour public subset is not the complete reported 100-hour training corpus; neither result is an independent cross-platform benchmark.',
    reviewedAt: '2026-08-22',
  },
  {
    id: 'robotacdex-humanoid-visual-tactile-action-dataset-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Four-view RGB-D synchronized with bilateral fingertip force, self-capacitance proximity, robot states, actions, and semantic annotations',
    modalities: ['four-view RGB', 'four-view depth', 'normal and tangential fingertip force', 'self-capacitance proximity', 'robot state', 'robot action', 'semantic annotation'],
    formFactor: 'Unitree G1 with fixed lower body, dual arms totaling 14 DoF, and two BrainCo Revo2 Tactile hands totaling 12 hand DoF as counted by the paper',
    dataOutput: 'More than 6,000 trajectories totaling approximately 25 hours across 19 tasks, an author-reported 23 skills, and 22 objects',
    applications: ['humanoid imitation learning', 'dual-arm dexterous manipulation', 'visual-tactile-action learning'],
    evidence: 'preprint',
    limitations: 'The June 2026 v1 preprint says the dataset will be open-sourced soon; no official package, repository, public file format, or dataset license was verified, and evaluation remains tied to one fixed-lower-body Unitree G1 configuration. The text reports 23 skills while Figure 4 exposes 22 discernible atomic-skill labels.',
    reviewedAt: '2026-08-22',
  },
  {
    id: 'tactidex-tactile-guided-dexterous-benchmark-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Alignment of whole-hand tactile signals with multi-granularity kinematic and object states',
    modalities: ['whole-hand tactile signal', 'kinematic state', 'object state', 'human demonstration'],
    formFactor: 'Real-world tactile-guided benchmark covering single-hand and bimanual dexterous tasks',
    dataOutput: 'Aligned demonstration data, standardized evaluation metrics, and a tri-component tactile reward',
    applications: ['human-to-robot skill transfer', 'contact-level manipulation evaluation', 'tactile-guided dexterity'],
    evidence: 'preprint',
    limitations: 'The reviewed abstract reports stronger success and physical realism without supplying a universal cross-hardware score; conclusions remain bound to the authors’ tasks, systems, metrics, and preprint evaluation.',
    reviewedAt: '2026-08-21',
  },
  {
    id: 'feelworld-visuo-tactile-world-model-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Action-conditioned hierarchical visual-tactile world modeling',
    modalities: ['visual latent', 'contact state', 'force-related 3D tactile latent', 'slip state', 'robot action'],
    formFactor: 'Contact-aware world model evaluated on chip grasping, fruit grasping, and USB insertion',
    dataOutput: 'Predicted visual futures, contact state, tactile latent, and slip state for contact-aware planning',
    applications: ['contact prediction', 'zero-shot robot planning', 'contact-rich manipulation'],
    evidence: 'preprint',
    limitations: 'Preprint evidence tied to three reported task setups, sensors, robot system, baselines, and planning protocol; LPIPS is not a direct force, slip, safety, or transfer metric.',
    reviewedAt: '2026-08-15',
  },
  {
    id: 'ht-bench-full-hand-tactile-representations-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Egocentric vision and full-hand tactile representation learning',
    modalities: ['egocentric RGB vision', 'full-hand tactile frames'],
    formFactor: 'Single reported egocentric/full-hand tactile pipeline spanning 226 data-collection tasks, plus four downstream real-robot tasks with 15 trials per method and task',
    dataOutput: '10M RGB frames and 7.8M tactile frames, four representation-learning tracks, and source-reported downstream task success rates',
    applications: ['tactile representation learning', 'dexterous manipulation', 'cross-modal prediction', 'bounded downstream robot evaluation'],
    evidence: 'preprint',
    limitations: 'The v2 preprint is tied to one reported egocentric/full-hand tactile sensing pipeline. The authors list fingertip optical tactile sensors, force/torque sensors, skin-like taxel arrays, and non-hand embodiments as uncovered. The 68.3% HandTouch mean versus the strongest baseline mean of 50.0% comes from four tasks with 15 trials each and no reported confidence intervals or significance test; it is not universal generalization evidence. Data, protocols, weights, and scripts are promised for future release and were not verified as downloadable on 2026-08-22.',
    reviewedAt: '2026-08-22',
  },
  {
    id: 'dream-tac-tactile-world-action-model-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Tactile world-action modeling',
    modalities: ['tactile observation', 'robot action'],
    formFactor: 'Contact-rich robot manipulation system',
    dataOutput: 'Predicted tactile observations conditioned on robot actions',
    applications: ['contact prediction', 'robot manipulation'],
    evidence: 'preprint',
    limitations: 'Preprint evidence; transfer across sensors, tasks, and deployment conditions still requires independent validation.',
    reviewedAt: '2026-07-10',
  },
  {
    id: 'single-material-soft-robotic-skin-2025',
    year: 2025,
    publisher: 'Science Robotics',
    sensorPrinciple: 'Single-layer conductive hydrogel with high-density electrical impedance tomography',
    modalities: ['touch and insulated presses', 'strain and proprioception', 'damage', 'local heating', 'temperature and humidity'],
    formFactor: 'Full-size hollow hydrogel hand with 32 wrist electrodes',
    dataOutput: 'Up to 863,040 electrode configurations yielding 1,726,080 amplitude-and-phase information channels',
    applications: ['robot body sensing', 'multimodal e-skin'],
    evidence: 'peer-reviewed',
    limitations: 'The 33 kHz maximum applies to one electrode configuration, while all 1,726,080 channels are reported at 0.02 Hz; durability, production integration, and real-world robotic-task testing remain open.',
    reviewedAt: '2026-08-22',
  },
  {
    id: 'freetacman-robot-free-visuotactile-data-collection-2025',
    year: 2025,
    publisher: 'arXiv',
    sensorPrinciple: 'Robot-free visuo-tactile data collection',
    modalities: ['vision-based touch', 'contact motion'],
    formFactor: 'Portable tactile data-collection workflow',
    dataOutput: 'Paired tactile observations and interaction trajectories',
    applications: ['tactile dataset collection', 'manipulation learning'],
    evidence: 'preprint',
    limitations: 'Preprint evidence; dataset diversity and transfer to other tactile hardware remain evaluation questions.',
    reviewedAt: '2026-07-10',
  },
  {
    id: 'sparsh-x-multisensory-touch-representations-2025',
    year: 2025,
    publisher: 'arXiv',
    sensorPrinciple: 'Multisensory tactile representation learning',
    modalities: ['tactile images', 'audio', 'motion', 'pressure'],
    formFactor: 'Digit 360 multisensory tactile representation model',
    dataOutput: 'Reusable latent touch representations',
    applications: ['physical property inference', 'contact-rich manipulation'],
    evidence: 'preprint',
    limitations: 'Preprint evidence; downstream performance depends on sensor coverage, task data, and evaluation protocol.',
    reviewedAt: '2026-07-10',
  },
  {
    id: 'genforce-transferable-force-sensing-2026',
    year: 2026,
    publisher: 'Nature Communications',
    sensorPrinciple: 'Cross-sensor force estimation through shared marker representations',
    modalities: ['three-axis force', 'optical and electronic tactile signals'],
    formFactor: 'Framework spanning GelSight, TacTip, and uSkin sensors',
    dataOutput: 'Estimated contact-force vectors',
    applications: ['force-aware manipulation', 'sensor transfer'],
    evidence: 'peer-reviewed',
    limitations: 'Published evaluation does not establish equivalent accuracy for every sensor geometry, material, or deployment environment.',
    reviewedAt: '2026-07-10',
  },
  {
    id: 'mitas-multi-resolution-tactile-imitation-learning-2026',
    year: 2026,
    publisher: 'arXiv',
    sensorPrinciple: 'Multi-resolution tactile imitation learning',
    modalities: ['vision-based touch', 'event-based touch'],
    formFactor: 'Tactile robot-hand learning pipeline',
    dataOutput: 'Time-aligned multisensor tactile features and robot actions',
    applications: ['imitation learning', 'dexterous manipulation'],
    evidence: 'preprint',
    limitations: 'Preprint evidence; benefits may depend on task dynamics, sensor timing, and the selected imitation-learning policy.',
    reviewedAt: '2026-07-10',
  },
  {
    id: 'ros2-kilted-tactile-pipeline-2026',
    year: 2026,
    publisher: 'Open Robotics documentation and RoboSkin.ai analysis',
    sensorPrinciple: 'ROS 2 tactile data transport and synchronization',
    modalities: ['pressure', 'shear', 'slip', 'temperature'],
    formFactor: 'Robot middleware pipeline',
    dataOutput: 'Timestamped tactile messages, transforms, and replayable logs',
    applications: ['robot integration', 'tactile dataset logging'],
    evidence: 'documentation',
    limitations: 'Architecture guidance rather than a benchmark; message design and timing requirements remain application-specific.',
    reviewedAt: '2026-07-10',
  },
  {
    id: 'humanoid-visual-tactile-action-dataset-2025',
    year: 2025,
    publisher: 'GIST arXiv preprint',
    sensorPrinciple: 'Dense humanoid-hand tactile sensing synchronized with vision, proprioception, and actions',
    modalities: ['848 × 480 egocentric vision', 'RealSense D435 third-person vision', 'dense hand tactile pressure', 'piezoresistive carpet pressure', 'arm and finger proprioception', 'robot actions'],
    formFactor: 'Unnamed teleoperated humanoid with two Inspire RH56-DFX hands and 1,062 tactile sensing units per hand',
    dataOutput: '101.9K visual-tactile-action samples with 2,124 total hand tactile values',
    applications: ['soft-object manipulation learning', 'visual-tactile-action policy training', 'dense tactile representation research'],
    evidence: 'preprint',
    limitations: 'One unnamed humanoid embodiment, two soft objects, four pressure conditions, and three operators; as of 2026-08-22 no official dataset download, code, project page, or dataset license was verified, and the arXiv CC BY license covers the article rather than unpublished data files.',
    reviewedAt: '2026-08-22',
  },
  {
    id: 'wet-slippage-bionic-fingertip-eskin-2026',
    year: 2026,
    publisher: 'Scientific Reports',
    sensorPrinciple: 'Fingerprint-patterned ferroelectric piezoelectric microvibration sensing',
    modalities: ['dynamic slip microvibration', 'surface-material and wetness-dependent waveform'],
    formFactor: 'Fully printed flexible fingertip e-skin mounted on a soft robotic hand',
    dataOutput: 'Slip-voltage waveforms with FFT and STFT features for wetness and surface classification',
    applications: ['wet and oily slip detection', 'robotic grasp monitoring', 'surface-material classification'],
    evidence: 'peer-reviewed',
    limitations: 'Classification used 120 mixed-condition signals and a small set of food objects; closed-loop grip correction, abrasion, cleaning, and long-term surface wear were not demonstrated.',
    reviewedAt: '2026-07-21',
  },
  {
    id: 'spiking-touch-encoding-large-area-eskin-2026',
    year: 2026,
    publisher: 'Nature Communications',
    sensorPrinciple: 'Fiber Bragg Grating strain sensing with event-driven spiking neural decoding',
    modalities: ['contact strain', 'spike-encoded touch events', 'single- and multi-touch location'],
    formFactor: '135 cm2 silicone forearm-shaped e-skin with 21 FBGs on one optical fiber and a neuromorphic processor',
    dataOutput: 'FBG wavelength shifts converted to spike trains and decoded into two-dimensional contact positions',
    applications: ['large-area touch localization', 'energy-constrained robotic skin', 'safe human-robot interaction'],
    evidence: 'peer-reviewed',
    limitations: 'The work is a 135 cm2 contact-localization demonstrator; error increased with contact count and body-scale transfer was not shown.',
    reviewedAt: '2026-07-21',
  },
  {
    id: 'origami-capacitive-robotic-eskin-2026',
    year: 2026,
    publisher: 'npj Flexible Electronics',
    sensorPrinciple: 'Origami deformation transmission with capacitive normal-force, shear, and proximity sensing',
    modalities: ['normal force', 'shear force', 'contact location', 'conductive-object proximity'],
    formFactor: '60,000 mm2 multilayer origami e-skin mounted as four curved modules on a robotic arm',
    dataOutput: 'Capacitance vectors decoded into load location, force magnitude, shear direction, and proximity',
    applications: ['large-area robot skin', 'collision-aware human-robot interaction', 'multi-point touch localization'],
    evidence: 'peer-reviewed',
    limitations: 'Adjacent loads can merge, proximity sensing is limited to conductive objects, and the multilayer structure still requires broader deployment validation.',
    reviewedAt: '2026-07-21',
  },
  {
    id: 'slip-actuated-etextile-tactile-sensing-2025',
    year: 2025,
    publisher: 'Nature Communications',
    sensorPrinciple: 'Tribovoltaic dynamic-DC slip sensing paired with capacitive normal-force sensing',
    modalities: ['dynamic slip', 'normal force', 'sliding direction and velocity-dependent response'],
    formFactor: 'Stretchable PEDOT:PSS E-textile integrated on robotic fingers',
    dataOutput: 'Self-powered DC slip voltage and capacitive force signals used by a feedback controller',
    applications: ['closed-loop slip mitigation', 'dexterous grasp monitoring', 'robotic manipulation'],
    evidence: 'peer-reviewed',
    limitations: 'Tests used a specific titanium-textile interface and controlled gripper disturbances; durability and coating wear need broader deployment evidence.',
    reviewedAt: '2026-07-21',
  },
  {
    id: 'dexskin-high-coverage-conformable-robotic-skin-2025',
    year: 2025,
    publisher: 'arXiv',
    sensorPrinciple: 'Conformable parallel-plate capacitive taxel skin with cross-instance calibration',
    modalities: ['localized normal force', 'distributed multi-contact patterns'],
    formFactor: 'Tailorable soft skin covering the dome and 294 degrees around parallel-jaw gripper fingers',
    dataOutput: 'Per-taxel capacitance readings and calibrated normal-force heatmaps',
    applications: ['in-hand reorientation', 'elastic-band packaging', 'delicate object manipulation', 'robot learning'],
    evidence: 'preprint',
    limitations: 'Robot experiments used a parallel-jaw gripper; an angular blind spot remains, policy inputs ignore spatial structure, and grounding relies on external jumper wires.',
    reviewedAt: '2026-07-21',
  },
  {
    id: 'full-hand-tactile-sensing-2025',
    year: 2025,
    publisher: 'Nature Machine Intelligence',
    sensorPrinciple: 'Vision-based photometric-stereo sensing of elastomer deformation',
    modalities: ['distributed contact geometry', 'contact location', 'in-hand object pose'],
    formFactor: '15-DoF anthropomorphic hand with 17 vision-based tactile sensors covering 70% of the palmar surface',
    dataOutput: 'Tactile images reconstructed into normal maps, contact geometry, and object-pose estimates',
    applications: ['adaptive multi-object grasping', 'collision-aware replanning', 'dexterous manipulation'],
    evidence: 'peer-reviewed',
    limitations: 'Results come from one custom hand and one task family; the controller assumes known object geometry and coverage is not complete hand or body coverage.',
    reviewedAt: '2026-07-21',
  },
  {
    id: 'temperature-pressure-bimodal-2025',
    year: 2025,
    publisher: 'Journal of Materials Chemistry C',
    sensorPrinciple: 'Review of separate- and shared-output temperature and pressure sensor architectures and decoupling methods',
    modalities: ['pressure', 'temperature'],
    formFactor: 'Survey of flexible layered, sandwich, and stacked bimodal tactile sensors',
    dataOutput: 'Separate or algorithmically decoupled pressure and temperature measurements',
    applications: ['robot tactile and thermal perception', 'human-machine interaction', 'wearable and environmental monitoring'],
    evidence: 'peer-reviewed',
    limitations: 'This is a review rather than a single-device benchmark; crosstalk, environmental interference, interface compatibility, and long-term stability remain unresolved.',
    reviewedAt: '2026-07-21',
  },
  {
    // The DOI includes 2025, but Crossref records formal publication on 2026-01-23.
    id: 'event-based-opto-tactile-2025',
    year: 2026,
    publisher: 'Frontiers in Neuroscience',
    sensorPrinciple: 'Stereo Dynamic Vision Sensors observing deformation-induced light changes in a silicone optical waveguide',
    modalities: ['contact-change events', 'single-touch location'],
    formFactor: 'Flexible silicone optical-waveguide skin viewed laterally by two DVS cameras',
    dataOutput: 'Sparse polarity events clustered and triangulated into two-dimensional contact positions',
    applications: ['large-area soft-robot touch localization', 'low-bandwidth interactive surfaces'],
    evidence: 'peer-reviewed',
    limitations: 'The proof of concept used fixed-depth single presses, did not estimate force or multi-touch, and processed trials offline.',
    reviewedAt: '2026-07-21',
  },
  {
    id: 'large-area-flexible-tactile-arrays-2025',
    year: 2025,
    publisher: 'ACS Applied Electronic Materials',
    sensorPrinciple: 'Skin-inspired rhombic-grid electrode array for spatial contact-force sensing',
    modalities: ['contact-force distribution', 'time-varying contact and slip', 'gesture trajectory'],
    formFactor: 'Large-area high-resolution flexible tactile array designed for curved surfaces',
    dataOutput: 'Spatial contact-force maps and contact-motion direction and velocity estimates',
    applications: ['curved robotic skin', 'slip and gesture detection', 'human-machine interaction'],
    evidence: 'peer-reviewed',
    limitations: 'Published evidence covers controlled curved-surface tests; whole-robot mounting, connector and data-rate behavior, contamination, and field repair are not established.',
    reviewedAt: '2026-07-21',
  },
];

export const researchIndexEntries = supplements.map(toEntry);

const csvColumns: (keyof ResearchIndexEntry)[] = [
  'id',
  'title',
  'url',
  'year',
  'publisher',
  'sourceTitle',
  'sourceUrl',
  'sensorPrinciple',
  'modalities',
  'formFactor',
  'dataOutput',
  'applications',
  'evidence',
  'limitations',
  'reviewedAt',
];

function csvCell(value: string | number | string[]): string {
  const text = Array.isArray(value) ? value.join('; ') : String(value);
  return `"${text.replaceAll('"', '""')}"`;
}

export function serializeResearchIndexCsv(entries = researchIndexEntries): string {
  const rows = entries.map((entry) => csvColumns.map((column) => csvCell(entry[column])).join(','));
  return `${csvColumns.join(',')}\n${rows.join('\n')}\n`;
}
