export type TactileSensorEntry = {
  id: string;
  name: string;
  organization: string;
  principle: string;
  formFactor: string;
  signals: string[];
  reportedRate: string;
  integration: string;
  access: string;
  evidenceBoundary: string;
  sourceUrl: string;
  projectUrl?: string;
  codeUrl?: string;
  manufacturerEvidenceUrl?: string;
  sourceReviewed: string;
};

export const tactileSensorEntries: TactileSensorEntry[] = [
  {
    id: 'digit',
    name: 'DIGIT',
    organization: 'Meta AI Research / GelSight',
    principle: 'Vision-based tactile sensing',
    formFactor: 'Compact robotic fingertip',
    signals: ['High-resolution tactile RGB image', 'Contact geometry cues'],
    reportedRate: 'Not publicly stated on the reviewed project page',
    integration: 'Designed for in-hand manipulation; open manufacturing design and interface repositories are available.',
    access: 'Open design files; commercial units have been offered through GelSight.',
    evidenceBoundary: 'Raw images do not automatically provide calibrated force, slip, or task success; those outputs depend on models and calibration.',
    sourceUrl: 'https://arxiv.org/abs/2005.14679',
    projectUrl: 'https://digit.ml/digit.html',
    codeUrl: 'https://github.com/facebookresearch/digit-design',
    sourceReviewed: '2026-08-19',
  },
  {
    id: 'digit-360',
    name: 'Digit 360',
    organization: 'Meta AI Research / GelSight',
    principle: 'Multimodal vision-based tactile sensing',
    formFactor: 'Hemispherical compliant fingertip',
    signals: ['Tactile image', 'Audio', 'Motion / IMU', 'Pressure', 'Other on-device sensing features'],
    reportedRate: 'Not publicly stated on the reviewed repository overview',
    integration: 'ROS 2 resources and a modular five-PCB sensor design are provided by the official repository.',
    access: 'Research design/software repository and call-for-proposals access path; verify current hardware availability.',
    evidenceBoundary: 'The source reports approximately 8.3 million image-derived taxels and more than 18 sensing features; deployment performance still depends on task-specific processing.',
    sourceUrl: 'https://ai.meta.com/blog/fair-robotics-open-source/',
    projectUrl: 'https://github.com/facebookresearch/digit360',
    codeUrl: 'https://github.com/facebookresearch/digit360',
    sourceReviewed: '2026-08-19',
  },
  {
    id: 'gelsight-mini',
    name: 'GelSight Mini',
    organization: 'GelSight',
    principle: 'Vision-based tactile sensing',
    formFactor: 'Compact flat tactile sensor',
    signals: ['Tactile RGB image', 'Surface topography cues', 'Marker motion for shear estimation'],
    reportedRate: '25 FPS in the reviewed official datasheet',
    integration: 'USB camera workflow with Linux, Windows, macOS, ROS, and ROS 2 support documented by GelSight.',
    access: 'Commercial hardware with a user-replaceable gel cartridge.',
    evidenceBoundary: 'The official datasheet reports an 18.6 × 14.3 mm field of view; task-level force or slip accuracy requires a defined model and protocol.',
    sourceUrl: 'https://www.gelsight.com/wp-content/uploads/productsheet/Mini/GelSight_Datasheet_GSMini.pdf',
    projectUrl: 'https://www.gelsightmini.com/',
    codeUrl: 'https://github.com/gelsightinc/gsrobotics',
    sourceReviewed: '2026-08-19',
  },
  {
    id: 'reskin',
    name: 'ReSkin',
    organization: 'Meta AI Research / Carnegie Mellon University',
    principle: 'Magnetic tactile skin',
    formFactor: 'Thin replaceable skin patch',
    signals: ['Three-axis magnetic tactile signal', 'Contact location', 'Force-related deformation'],
    reportedRate: 'Up to 400 Hz reported by Meta',
    integration: 'Passive magnetized elastomer is separated from nearby magnetometer electronics for replaceable skin interfaces.',
    access: 'Open-source design, documentation, code, and base-model release described by Meta.',
    evidenceBoundary: 'Meta reports 2–3 mm thickness, more than 50,000 interactions, and 1 mm spatial resolution at 90% accuracy under its evaluation; do not generalize those figures to every geometry.',
    sourceUrl: 'https://ai.meta.com/blog/reskin-a-versatile-replaceable-low-cost-skin-for-ai-research-on-tactile-perception/',
    sourceReviewed: '2026-08-19',
  },
  {
    id: 'anyskin',
    name: 'AnySkin',
    organization: 'New York University / Carnegie Mellon University / Columbia University / Meta',
    principle: 'Magnetic tactile skin',
    formFactor: 'Replaceable skin interface for robot end effectors',
    signals: ['Magnetic-field distortion', 'Contact', 'Slip-related signal'],
    reportedRate: 'Not publicly stated on the reviewed project page',
    integration: 'Adhesive-free mechanical designs target fast replacement across grippers and robot hands.',
    access: 'Project page links paper, code, CAD files, design tool, and sample / purchase paths.',
    evidenceBoundary: 'The paper evaluates cross-instance policy reuse on its tasks; it does not establish calibration-free equivalence across all robot geometries.',
    sourceUrl: 'https://arxiv.org/abs/2409.08276',
    projectUrl: 'https://any-skin.github.io/',
    sourceReviewed: '2026-08-19',
  },
  {
    id: 'gelslim-4',
    name: 'GelSlim 4.0',
    organization: 'University of Michigan MMint Lab',
    principle: 'Vision-based tactile sensing',
    formFactor: 'Compact tactile finger for parallel grippers',
    signals: ['Tactile image', 'Contact shape', 'Marker displacement cues'],
    reportedRate: 'Not publicly stated in the reviewed abstract',
    integration: 'Open-source design emphasizes reproducibility, a modifiable finger structure, and manufacturable lenses.',
    access: 'Project documentation, code, and data are linked by the paper.',
    evidenceBoundary: 'It is a research sensor design; calibrated force, slip, and manipulation results depend on the associated processing and task setup.',
    sourceUrl: 'https://arxiv.org/abs/2409.19770',
    projectUrl: 'https://www.mmintlab.com/research/gelslim-4-0/',
    sourceReviewed: '2026-08-19',
  },
  {
    id: 'tactip',
    name: 'TacTip',
    organization: 'Bristol Robotics Laboratory / University of Bristol',
    principle: 'Biomimetic optical tactile sensing',
    formFactor: 'Soft 3D-printed fingertip and related morphologies',
    signals: ['Internal marker displacement', 'Contact shape', 'Shear and slip cues'],
    reportedRate: 'Depends on the camera and TacTip variant; no single rate is stated for the full family',
    integration: 'Open 3D-printed sensor family used in tactile perception, servoing, manipulation, and simulation research.',
    access: 'Research designs and publications are openly documented; verify the current variant and files.',
    evidenceBoundary: 'TacTip is a sensor family, not one fixed specification. Geometry, camera, skin, markers, and inference pipeline vary by version.',
    sourceUrl: 'https://arxiv.org/abs/2105.14455',
    projectUrl: 'https://www.tactip.org/',
    sourceReviewed: '2026-08-19',
  },
  {
    id: 'biotac',
    name: 'BioTac',
    organization: 'SynTouch',
    principle: 'Fluid-filled biomimetic multimodal sensing',
    formFactor: 'Human-fingertip-shaped sensor',
    signals: ['Force-related electrode impedance', 'Fluid pressure', 'Vibration', 'Temperature / heat flow'],
    reportedRate: 'No single cross-modality rate is used in this directory; BioTac signal channels and hardware revisions must be checked separately.',
    integration: 'The reviewed peer-reviewed source describes the biomimetic multimodal sensor; current hand integrations, software support, and connectors require separate verification.',
    access: 'Historically commercial hardware; current sales, support, and availability were not verified in this review.',
    evidenceBoundary: 'The curved compliant device provides multiple raw modalities, while explicit force vectors require calibration or learned interpretation. BioTac and BioTac SP revisions must not be conflated, and the former product domain is not treated as current evidence.',
    sourceUrl: 'https://doi.org/10.7210/jrsj.30.496',
    manufacturerEvidenceUrl: 'https://www.sec.gov/Archives/edgar/data/1728560/000172856021000002/SynTouchFormC-AR-2021-04-30.pdf',
    sourceReviewed: '2026-08-22',
  },
  {
    id: 'uskin',
    name: 'uSkin',
    organization: 'XELA Robotics',
    principle: 'Distributed magnetic three-axis force sensing',
    formFactor: 'Soft modular arrays for fingers, palms, grippers, and custom surfaces',
    signals: ['Normal force per taxel', 'Two-axis shear force per taxel'],
    reportedRate: 'Up to 500 Hz for the uSPa 11 model in the reviewed catalog',
    integration: 'Digital-output modules can contain up to 64 sensing points and connect to XELA processing software.',
    access: 'Commercial hardware in multiple shapes and robot-hand integrations.',
    evidenceBoundary: 'Range, resolution, rate, thickness, and taxel count differ by model; compare the exact datasheet rather than applying one model’s specification to the family.',
    sourceUrl: 'https://xelarobotics.com/wp-content/uploads/2025/12/XELA-Robotics-Product-Catalog-2025-EN.pdf',
    projectUrl: 'https://xelarobotics.com/products/uscu-alha/',
    sourceReviewed: '2026-08-19',
  },
  {
    id: 'densetact-2',
    name: 'DenseTact 2.0',
    organization: 'Stanford University ARM Lab',
    principle: 'Vision-based optical tactile sensing',
    formFactor: 'Highly curved soft robotic fingertip',
    signals: ['Deformed-surface image', 'Calibrated shape reconstruction', 'Six-axis wrench estimate'],
    reportedRate: 'Not publicly stated in the reviewed abstract',
    integration: 'Designed for compact dexterous manipulation and calibrated through learned shape and wrench models.',
    access: 'Research paper and associated laboratory resources.',
    evidenceBoundary: 'Reported shape and wrench errors come from the paper calibration setup; transfer to a new finger still requires calibration data and validation.',
    sourceUrl: 'https://arxiv.org/abs/2209.10122',
    projectUrl: 'https://arm.stanford.edu/research/improving-robotic-assistant-dexterity',
    sourceReviewed: '2026-08-19',
  },
  {
    id: '9dtact',
    name: '9DTact',
    organization: 'Shanghai Qi Zhi Institute / Tsinghua University / HUST / Shanghai AI Laboratory',
    principle: 'Vision-based tactile sensing with translucent gel',
    formFactor: 'Compact tactile fingertip',
    signals: ['Tactile image', '3D shape reconstruction', 'Six-axis force estimate'],
    reportedRate: 'Not publicly stated on the reviewed project page',
    integration: 'Open hardware, software, dataset, pretrained models, and fabrication tutorial are provided.',
    access: 'Fully open-source research design according to the official project page.',
    evidenceBoundary: 'The reported generalizable force model uses approximately 100,000 image-force pairs from 175 objects; unseen hardware and tasks require separate validation.',
    sourceUrl: 'https://arxiv.org/abs/2308.14277',
    projectUrl: 'https://linchangyi1.github.io/9DTact/',
    codeUrl: 'https://github.com/linchangyi1/9DTact',
    sourceReviewed: '2026-08-19',
  },
  {
    id: 'insight',
    name: 'Insight',
    organization: 'Max Planck Institute for Intelligent Systems',
    principle: 'Vision-based haptic sensing',
    formFactor: 'Soft thumb-sized conical sensor',
    signals: ['Directional three-axis force-distribution map', 'Contact location', 'Contact shape cues'],
    reportedRate: 'Not publicly stated on the reviewed project page',
    integration: 'The design maps camera observations to distributed force vectors across a three-dimensional surface.',
    access: 'Research publication and project documentation.',
    evidenceBoundary: 'The published force-map performance belongs to the paper hardware, data, and learned calibration, not every derived sensor shape.',
    sourceUrl: 'https://www.nature.com/articles/s42256-021-00439-3',
    projectUrl: 'https://is.mpg.de/hi/en/projects/insight-a-haptic-sensor-powered-by-vision-and-machine-learning',
    sourceReviewed: '2026-08-19',
  },
  {
    id: 'allsight',
    name: 'AllSight',
    organization: 'Ben-Gurion University research team',
    principle: 'Vision-based optical tactile sensing',
    formFactor: 'Round thumb-sized tactile sensor',
    signals: ['Contact position', 'Force', 'Torsion', 'Tactile image'],
    reportedRate: 'Not publicly stated in the reviewed abstract',
    integration: 'Mostly 3D-printed modular design targets in-hand manipulation and broad curved-surface contact.',
    access: 'Open-source research design linked by the paper.',
    evidenceBoundary: 'The paper’s zero-shot claim concerns state-estimation transfer across fabricated instances under its protocol, not zero-shot transfer to every task or robot.',
    sourceUrl: 'https://arxiv.org/abs/2307.02928',
    sourceReviewed: '2026-08-19',
  },
];
